package com.example.ecochef

import androidx.compose.runtime.mutableStateListOf
import androidx.compose.runtime.remember

data class Ingredients (var Iname : String, var imageInt: Int = R.drawable.custom_ing, var custom: Boolean = false)


fun getIngredientsList(): MutableList<Ingredients> {
    val ingredientsList = mutableStateListOf<Ingredients>()
    ingredientsList.add(Ingredients("Burger", R.drawable.beef_burger))
    ingredientsList.add(Ingredients("Almond",R.drawable.almond))
    ingredientsList.add(Ingredients("Anchovies",R.drawable.anchovy))
    ingredientsList.add(Ingredients("Apple",R.drawable.apple))
    ingredientsList.add(Ingredients("Apricot",R.drawable.apricot))
    ingredientsList.add(Ingredients("Artichoke",R.drawable.artichoke))
    ingredientsList.add(Ingredients("Asparagus",R.drawable.asparagus))
    ingredientsList.add(Ingredients("Aubergine",R.drawable.aubergine))
    ingredientsList.add(Ingredients("Avocado",R.drawable.avocado))
    ingredientsList.add(Ingredients("Bacon",R.drawable.bacon))
    ingredientsList.add(Ingredients("Bagel",R.drawable.bagel))
    ingredientsList.add(Ingredients("Baguette", R.drawable.baguette))
    ingredientsList.add(Ingredients("Banana", R.drawable.banana))
    ingredientsList.add(Ingredients("Basil", R.drawable.basil))
    ingredientsList.add(Ingredients("Beef", R.drawable.beef_mince))
    ingredientsList.add(Ingredients("Beer", R.drawable.beer))
    ingredientsList.add(Ingredients("Biscuits", R.drawable.biscuit))
    ingredientsList.add(Ingredients("Blackberry", R.drawable.blackberry))
    ingredientsList.add(Ingredients("Blackcurrant", R.drawable.blackcurrants))
    ingredientsList.add(Ingredients("Blueberry", R.drawable.blueberry))
    ingredientsList.add(Ingredients("Bread", R.drawable.bread))
    ingredientsList.add(Ingredients("Brie", R.drawable.brie_cheese))
    ingredientsList.add(Ingredients("Brioche", R.drawable.brioche))
    ingredientsList.add(Ingredients("Broccoli", R.drawable.broccoli))
    ingredientsList.add(Ingredients("Butter", R.drawable.butter))
    ingredientsList.add(Ingredients("Cabbage", R.drawable.cabbage))
    ingredientsList.add(Ingredients("Caramel", R.drawable.caramel))
    ingredientsList.add(Ingredients("Carrot", R.drawable.carrot))
    ingredientsList.add(Ingredients("Cauliflower", R.drawable.cauliflower))
    ingredientsList.add(Ingredients("Celery", R.drawable.celery))
    ingredientsList.add(Ingredients("Cheddar", R.drawable.cheddar_cheese))
    ingredientsList.add(Ingredients("Cherry", R.drawable.cherry))
    ingredientsList.add(Ingredients("Chicken", R.drawable.chicken))
    ingredientsList.add(Ingredients("Chilli", R.drawable.chilli))
    ingredientsList.add(Ingredients("Chocolate", R.drawable.chocolate))
    ingredientsList.add(Ingredients("Chorizo", R.drawable.chorizo))
    ingredientsList.add(Ingredients("Cinnamon", R.drawable.cinnamon))
    ingredientsList.add(Ingredients("Cod", R.drawable.cod))
    ingredientsList.add(Ingredients("Coffee", R.drawable.coffee_beans))
    ingredientsList.add(Ingredients("Crab", R.drawable.crab))
    ingredientsList.add(Ingredients("Cream", R.drawable.cream))
    ingredientsList.add(Ingredients("Cucumber", R.drawable.cucumber))
    ingredientsList.add(Ingredients("Duck", R.drawable.duck))
    ingredientsList.add(Ingredients("Egg", R.drawable.egg))
    ingredientsList.add(Ingredients("Fish", R.drawable.fish))
    ingredientsList.add(Ingredients("Flour", R.drawable.flour))
    ingredientsList.add(Ingredients("Gammon", R.drawable.gammon))
    ingredientsList.add(Ingredients("Garlic", R.drawable.garlic))
    ingredientsList.add(Ingredients("Gelatine", R.drawable.gelatine))
    ingredientsList.add(Ingredients("Ginger", R.drawable.ginger))
    ingredientsList.add(Ingredients("Gnocchi", R.drawable.gnocchi))
    ingredientsList.add(Ingredients("Gravy", R.drawable.gravy))
    ingredientsList.add(Ingredients("Haddock", R.drawable.haddock))
    ingredientsList.add(Ingredients("Halloumi", R.drawable.halloumi_cheese))
    ingredientsList.add(Ingredients("Ham", R.drawable.ham))
    ingredientsList.add(Ingredients("Hazelnut", R.drawable.hazelnut))
    ingredientsList.add(Ingredients("Honey", R.drawable.honey))
    ingredientsList.add(Ingredients("Hummus", R.drawable.hummus))
    ingredientsList.add(Ingredients("Kiwi", R.drawable.kiwi_fruit))
    ingredientsList.add(Ingredients("lamb", R.drawable.lamb))
    ingredientsList.add(Ingredients("Lardons", R.drawable.lardons))
    ingredientsList.add(Ingredients("Lasagne", R.drawable.lasagne))
    ingredientsList.add(Ingredients("Lemon", R.drawable.lemon))
    ingredientsList.add(Ingredients("Lettuce", R.drawable.lettuce))
    ingredientsList.add(Ingredients("Lobster", R.drawable.lobster))
    ingredientsList.add(Ingredients("Macaroni", R.drawable.macaroni))
    ingredientsList.add(Ingredients("Mango", R.drawable.mango))
    ingredientsList.add(Ingredients("Milk", R.drawable.milk))
    ingredientsList.add(Ingredients("Mozzarella", R.drawable.mozzarella))
    ingredientsList.add(Ingredients("Mushroom", R.drawable.mushroom))
    ingredientsList.add(Ingredients("Noodles", R.drawable.noodle))
    ingredientsList.add(Ingredients("Oats", R.drawable.oats))
    ingredientsList.add(Ingredients("Onion", R.drawable.onion))
    ingredientsList.add(Ingredients("Orange", R.drawable.orange))
    ingredientsList.add(Ingredients("Pasta", R.drawable.pasta))
    ingredientsList.add(Ingredients("Peach", R.drawable.peach))
    ingredientsList.add(Ingredients("Pepper", R.drawable.pepper))
    ingredientsList.add(Ingredients("Pesto", R.drawable.pesto))
    ingredientsList.add(Ingredients("Pork", R.drawable.pork))
    ingredientsList.add(Ingredients("Potato", R.drawable.potato))
    ingredientsList.add(Ingredients("Sugar", R.drawable.sugar))
    return ingredientsList
}




